=== haroldfrost1/wsd/src/hotels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<!-- Custom Types -->
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z|_|\.]+[@]{1}[A-Za-z|\-|]+[\.]{1}[A-Za-z|\-]+([\.]{1}[A-Za-z|\-]+)*"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Schema -->
	<xs:element name="hotels">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="hotel" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="city" type="xs:string" />
							<xs:element name="country" type="xs:string" />
							<xs:element name="id" type="xs:positiveInteger" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="address" type="xs:string"/>
							<xs:element name="email" type="email"/>
							<xs:element name="telephone" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== haroldfrost1/wsd/src/hotels.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hotels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="hotels.xsd">
	<hotel>
		<city>Melbourne</city>
		<country>Australia</country>
		<id>1</id>
		<name>Pansione Hotel Melbourne</name>
		<address>16 Spam St, Melbourne, Victoria 3000, Australia</address>
		<email>book@pansione.fake.au</email>
		<telephone>1800-687-236</telephone>
	</hotel>
	<hotel>
		<city>New York</city>
		<country>USA</country>
		<id>2</id>
		<name>Hotel Pennshyvannas</name>
		<address>401 Fake Avenue, New York, NY 10001, USA</address>
		<email>pennshyvannas@fake.com</email>
		<telephone>+1(052)8888888</telephone>
	</hotel>
	<hotel>
		<city>London</city>
		<country>England</country>
		<id>3</id>
		<name>The Stran Palace</name>
		<address>372 Stran, London, WC2R 0JJ, United Kingdom</address>
		<email>reservations@stranpalacehotel.co.fake</email>
		<telephone>+44 207379 ABCD</telephone>
	</hotel>
</hotels>
